export const ACTION_TYPES = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  LOAD_CLIENT_STOCK_DATA: 'LOAD_CLIENT_STOCK_DATA',
  REGISTER: 'REGISTER',
  SET_AUTH_TOKEN: 'SET_AUTH_TOKEN',
  SET_CLIENT_STOCK_DATA: 'SET_CLIENT_STOCK_DATA',
  UPDATE_CLIENT_STOCK_DATA: 'UPDATE_CLIENT_STOCK_DATA',
  UPDATE_CLIENT_CASH_FLOWS: 'UPDATE_CLIENT_CASH_FLOWS',
  GET_CLIENT_CASH_FLOWS: 'GET_CLIENT_CASH_FLOWS',
  SET_CLIENT_CASH_FLOWS: 'SET_CLIENT_CASH_FLOWS',
  GET_CLIENT_EDIT_LOGS: 'GET_CLIENT_EDIT_LOGS',
  UPDATE_CLIENT_EDIT_LOGS: 'UPDATE_CLIENT_EDIT_LOGS',
  SET_CLIENT_EDIT_LOGS: 'SET_CLIENT_EDIT_LOGS',
  SET_CLIENT_CASH_AMOUNT: 'SET_CLIENT_CASH_AMOUNT',
  LOAD_CLIENT_ESTATE_DATA: 'LOAD_CLIENT_ESTATE_DATA',
  UPDATE_CLIENT_ESTATE_DATA: 'UPDATE_CLIENT_ESTATE_DATA',
  SET_CLIENT_ESTATE_DATA: 'SET_CLIENT_ESTATE_DATA'
}

export const NAV_DRAWER_WIDTH = 240;

export const FINNHUB_API_KEY = 'bpkk0b7rh5rcgrlrat4g';

export const SCREENS = {
  DASHBOARD: "Dashboard",
  STOCK: "Stock",
  ESTATE: "Estate",
  CASH: "Cash"
}
